"""create business persistence schema

Revision ID: 0001
Revises:
Create Date: 2026-08-11 18:55:08.924991

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookings",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "disruption_policies",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("rebooking_window_hours", sa.Integer(), nullable=False),
        sa.Column("allows_next_day", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "rebooking_window_hours > 0", name="ck_disruption_policies_positive_window"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "flights",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("carrier_code", sa.String(length=2), nullable=False),
        sa.Column("flight_number", sa.String(length=4), nullable=False),
        sa.Column("origin", sa.String(length=3), nullable=False),
        sa.Column("destination", sa.String(length=3), nullable=False),
        sa.Column("scheduled_departure", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_arrival", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "origin <> destination", name="ck_flights_distinct_airports"
        ),
        sa.CheckConstraint(
            "scheduled_arrival > scheduled_departure",
            name="ck_flights_arrival_after_departure",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "carrier_code",
            "flight_number",
            "scheduled_departure",
            name="uq_flights_scheduled_service",
        ),
    )
    op.create_index(
        "ix_flights_route_departure",
        "flights",
        ["origin", "destination", "scheduled_departure"],
        unique=False,
    )
    op.create_table(
        "passengers",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("given_name", sa.String(length=100), nullable=False),
        sa.Column("family_name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "booking_passengers",
        sa.Column("booking_id", sa.String(length=32), nullable=False),
        sa.Column("passenger_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["passenger_id"], ["passengers.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("booking_id", "passenger_id"),
    )
    op.create_index(
        "ix_booking_passengers_passenger_id",
        "booking_passengers",
        ["passenger_id"],
        unique=False,
    )
    op.create_table(
        "disruption_policy_types",
        sa.Column("policy_id", sa.String(length=32), nullable=False),
        sa.Column("disruption_type", sa.String(length=32), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "disruption_type IN ('delayed_flight', 'cancelled_flight', 'missed_connection')",
            name="ck_disruption_policy_types_supported_type",
        ),
        sa.CheckConstraint(
            "sequence > 0", name="ck_disruption_policy_types_positive_sequence"
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"], ["disruption_policies.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("policy_id", "disruption_type"),
        sa.UniqueConstraint(
            "policy_id", "sequence", name="uq_disruption_policy_types_sequence"
        ),
    )
    op.create_index(
        "ix_disruption_policy_types_type",
        "disruption_policy_types",
        ["disruption_type"],
        unique=False,
    )
    op.create_table(
        "itinerary_segments",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("booking_id", sa.String(length=32), nullable=False),
        sa.Column("flight_id", sa.String(length=32), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "sequence > 0", name="ck_itinerary_segments_positive_sequence"
        ),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["flight_id"], ["flights.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "booking_id", "flight_id", name="uq_itinerary_segments_booking_flight"
        ),
        sa.UniqueConstraint(
            "booking_id", "sequence", name="uq_itinerary_segments_booking_sequence"
        ),
        sa.UniqueConstraint("id", "flight_id", name="uq_itinerary_segments_id_flight"),
    )
    op.create_index(
        "ix_itinerary_segments_flight_id",
        "itinerary_segments",
        ["flight_id"],
        unique=False,
    )
    op.create_table(
        "disruptions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("affected_flight_id", sa.String(length=32), nullable=False),
        sa.Column("affected_segment_id", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("delay_minutes", sa.Integer(), nullable=True),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column("arriving_flight_id", sa.String(length=32), nullable=True),
        sa.Column("missed_flight_id", sa.String(length=32), nullable=True),
        sa.CheckConstraint(
            "(type = 'delayed_flight' AND delay_minutes IS NOT NULL AND delay_minutes > 0 AND cancellation_reason IS NULL AND arriving_flight_id IS NULL AND missed_flight_id IS NULL) OR (type = 'cancelled_flight' AND delay_minutes IS NULL AND cancellation_reason IS NOT NULL AND length(btrim(cancellation_reason)) > 0 AND arriving_flight_id IS NULL AND missed_flight_id IS NULL) OR (type = 'missed_connection' AND delay_minutes IS NULL AND cancellation_reason IS NULL AND arriving_flight_id IS NOT NULL AND missed_flight_id IS NOT NULL AND arriving_flight_id <> missed_flight_id AND affected_flight_id = missed_flight_id)",
            name="ck_disruptions_type_specific_details",
        ),
        sa.CheckConstraint(
            "type IN ('delayed_flight', 'cancelled_flight', 'missed_connection')",
            name="ck_disruptions_supported_type",
        ),
        sa.ForeignKeyConstraint(
            ["affected_flight_id"], ["flights.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["affected_segment_id", "affected_flight_id"],
            ["itinerary_segments.id", "itinerary_segments.flight_id"],
            name="fk_disruptions_affected_segment_flight",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["arriving_flight_id"], ["flights.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["missed_flight_id"], ["flights.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_disruptions_affected_flight_id",
        "disruptions",
        ["affected_flight_id"],
        unique=False,
    )
    op.create_index(
        "ix_disruptions_affected_segment_id",
        "disruptions",
        ["affected_segment_id"],
        unique=False,
    )
    op.create_table(
        "recovery_cases",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("booking_id", sa.String(length=32), nullable=False),
        sa.Column("disruption_id", sa.String(length=32), nullable=False),
        sa.Column("policy_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["disruption_id"], ["disruptions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"], ["disruption_policies.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_recovery_cases_booking_id", "recovery_cases", ["booking_id"], unique=False
    )
    op.create_index(
        "ix_recovery_cases_disruption_id",
        "recovery_cases",
        ["disruption_id"],
        unique=False,
    )
    op.create_index(
        "ix_recovery_cases_policy_id", "recovery_cases", ["policy_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_recovery_cases_policy_id", table_name="recovery_cases")
    op.drop_index("ix_recovery_cases_disruption_id", table_name="recovery_cases")
    op.drop_index("ix_recovery_cases_booking_id", table_name="recovery_cases")
    op.drop_table("recovery_cases")
    op.drop_index("ix_disruptions_affected_segment_id", table_name="disruptions")
    op.drop_index("ix_disruptions_affected_flight_id", table_name="disruptions")
    op.drop_table("disruptions")
    op.drop_index("ix_itinerary_segments_flight_id", table_name="itinerary_segments")
    op.drop_table("itinerary_segments")
    op.drop_index(
        "ix_disruption_policy_types_type", table_name="disruption_policy_types"
    )
    op.drop_table("disruption_policy_types")
    op.drop_index("ix_booking_passengers_passenger_id", table_name="booking_passengers")
    op.drop_table("booking_passengers")
    op.drop_table("passengers")
    op.drop_index("ix_flights_route_departure", table_name="flights")
    op.drop_table("flights")
    op.drop_table("disruption_policies")
    op.drop_table("bookings")
    # ### end Alembic commands ###
